// Generated by CoffeeScript 1.7.1
var app, config, db, express, fs, message, mongoose, question, restify;

express = require('express');

mongoose = require('mongoose');

restify = require('restify');

fs = require('fs');

question = require('./controllers/question');

message = require('./controllers/message');

config = require('./config');

app = restify.createServer();

app.use(restify.bodyParser({
  mapParams: false
}));

app.use(restify.queryParser());

mongoose.connect(config.database.machine + ':' + config["default"].port + '/' + config.database.DBName);

db = mongoose.connection;

db.on('error', console.error.bind(console, 'connection error'));

db.once('open', function() {
  app.post('/question/insert', question.insert);
  app.get('/question', question.all);
  app.get('/messages', message.all);
  app.post('/messages/insert', message.insert);
  app.post('/messages/incoming', message.incomingListener);
  app.post('/question/update', question.update);
  return app.listen(3000);
});
